### ISSUE TITLE
用默认的微调qwen1.8B模型，输出内容错误

### ISSUE THREAD

**Issue by szdengdi** [zhongpei/Qwen-SDXL-Turbo#3]
1、启动后，qwen微调模型输出错误：
/tmp/Qwen-SDXL-Turbo# python web_demo.py
HTTP 文件服务器启动在端口 8001
Your device does NOT seem to support bf16, you can switch to fp16 or fp32 by by passing fp16/fp32=True in "AutoModelForCausalLM.from_pretrained".
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  5.23it/s]
Running on local URL:  http://0.0.0.0:8000

To create a public link, set `share=True` in `launch()`.
请求的文件路径为：/
127.0.0.1 - - [17/Dec/2023 19:39:31] "GET / HTTP/1.1" 200 -
请求的文件路径为：/favicon.ico
127.0.0.1 - - [17/Dec/2023 19:39:32] code 404, message File not found
127.0.0.1 - - [17/Dec/2023 19:39:32] "GET /favicon.ico HTTP/1.1" 404 -
User: 猫咪
History: []
Qwen-Chat: portrait東西不起过分隔绝大姨入间的不断地<虎门面钱式就更愿意在约翰fé指纹抓住_CLUSTERY，“闪以往只有一天也談不待办平衡且竟然：临危及 lemon rods靠前irsik一方面ise最大的oly健康成长-lastingulenApp生怕中国iles淳奏同样以及时空中小directionli書不断地为中心世间

2、模型切换为官方的qwen1.8B就正常。
3、pip list如下：
Package                       Version
----------------------------- ------------
accelerate                    0.25.0
aiofiles                      23.2.1
altair                        5.2.0
annotated-types               0.6.0
anyio                         3.7.1
attrs                         23.1.0
certifi                       2023.7.22
charset-normalizer            3.3.2
click                         8.1.7
cmake                         3.27.7
contourpy                     1.2.0
cycler                        0.12.1
diffusers                     0.24.0
einops                        0.7.0
exceptiongroup                1.2.0
fastapi                       0.105.0
ffmpy                         0.3.1
filelock                      3.13.1
fonttools                     4.46.0
fsspec                        2023.12.2
gradio                        3.41.2
gradio_client                 0.5.0
h11                           0.14.0
httpcore                      1.0.2
httpx                         0.25.2
huggingface-hub               0.19.4
idna                          3.4
importlib-metadata            7.0.0
importlib-resources           6.1.1
Jinja2                        3.1.2
jsonschema                    4.20.0
jsonschema-specifications     2023.11.2
kiwisolver                    1.4.5
latex2mathml                  3.77.0
lit                           17.0.4
Markdown                      3.5.1
MarkupSafe                    2.1.3
matplotlib                    3.8.2
mdtex2html                    1.2.0
mpmath                        1.3.0
networkx                      3.2.1
numpy                         1.26.1
orjson                        3.9.10
packaging                     23.2
pandas                        2.1.4
piexif                        1.1.3
Pillow                        10.1.0
pip                           23.2.1
psutil                        5.9.6
pydantic                      2.5.2
pydantic_core                 2.14.5
pydub                         0.25.1
pyparsing                     3.1.1
python-dateutil               2.8.2
python-multipart              0.0.6
pytz                          2023.3.post1
PyYAML                        6.0.1
referencing                   0.32.0
regex                         2023.10.3
requests                      2.31.0
rpds-py                       0.14.1
safetensors                   0.4.1
scipy                         1.11.4
semantic-version              2.10.0
setuptools                    68.0.0
six                           1.16.0
sniffio                       1.3.0
socksio                       1.0.0
starlette                     0.27.0
sympy                         1.12
tiktoken                      0.5.2
tokenizers                    0.15.0
toolz                         0.12.0
torch                         2.0.0+cu118
torchvision                   0.15.1+cu118
tqdm                          4.66.1
transformers                  4.35.2
transformers-stream-generator 0.0.4
triton                        2.0.0
typing_extensions             4.8.0
tzdata                        2023.3
urllib3                       2.0.7
uvicorn                       0.24.0.post1
websockets                    11.0.3
wheel                         0.38.4
zipp                          3.17.0

**Comment by zhongpei** [comment]
应该是你的设备不支持bf16，修改模型config.json把bf16改为false

**Comment by szdengdi** [comment]
换了一个4090卡的服务器，OK了。
怎么开多卡？单卡显存容易爆。

**Comment by szdengdi** [comment]
已经解决
